name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dco-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check DCO sign-off
        uses: tisonkun/actions-dco@v1.1
